### ISSUE TITLE
Add a trust index for nodes

### ISSUE THREAD

**Issue by tomerweller** [stellarbeat/js-stellarbeat-frontend#3]
The current `Nodes` tab is a bit messy. There's a single view that combines validators with good reputation alongside anonymous ones. 

It would be great to maintain some sort of a "score card" for validators, display it, and even allow hiding validators that don't reach a specific threshold.

Some parameters that might affect the score: 
- Correct implementation of [SEP20](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0020.md) (Once that's finalized) 
- How recent the stellar-core version is. 
- Uptime (above 99%, for example)
- Is a full validator

**Comment by pieterjan84** [comment]
I added a basic index calculation to get the conversation started: [code](https://github.com/stellarbeat/js-stellar-domain/tree/master/src/node-index). You can view the results in the [nodes table](https://stellarbeat.io/nodes). 

Index = (TypeIndex + AvailabilityIndex + VersionIndex + TrustIndex + AgeIndex)/5

Type = Full validator | Basic validator | Watcher node
Availability = Active/available in the latest 300 crawls
Version = How far away from the latest stable Stellar core version
Trust = How many active validators trust this node
Age = Time since discovery

**Comment by tomerweller** [comment]
Maybe show that formula in the page? (when hovering on index or something like that)

**Comment by pieterjan84** [comment]
Added formula below nodes list. Also going to add a 'help page' with an faq, which will include the formula explanation.
